title: Jeroen Rijks
description: Jeroen Rijks's personal website and blog.
show_downloads: true

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://jeroenrijks.com" # change this to the base hostname & protocol for your site

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: jekyll-theme-cayman

# social
author: Jeroen Rijks
