title:              Jeroen Rijks
email:              jeroen-rijks@hotmail.com
description:        Jeroen's blog
author:             Jeroen Rijks
baseurl:            ""
url:                "https://jeroenrijks.github.io"

# Social Profiles
github_username:    JeroenRijks
linkedin_username: JeroenRijks

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
